### ISSUE TITLE
rsp.assembly.json configuration not applied when deploying to Tomcat

### ISSUE THREAD

**Issue by ExodusG** [redhat-developer/vscode-rsp-ui#314]
Hey,

I'm coding on Eclipse. But I want to change for another IDE for many reasons. I'm using a Tomcat 10 server with a Java Spring app. I'm trying to migrate my project to VSCode with the extension "Runtime Server Protocol UI" and "Community Server Connectors". The server is starting but not the app inside it. So I have started to investigate and I have notice that I have set up the rsp.assembly.json but it seems that the extension doesn’t take this file and just copies the whole project folder to the serverlocation/wtpwebapps/projectName.

Did I miss something in the configuration?

The rsp.assembly.json : 
```json
{
	"mappings": [
		{
			"source-path": "target/m2e-wtp/web-resources/",
			"deploy-path": "/"
		},
		{
			"source-path": "src/main/webapp/",
			"deploy-path": "/"
		},
		{
			"source-path": "src/main/java/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "target/metamodel/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "src/main/resources/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "src/main/wsdl/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "conf/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "conf/dev/resources/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": ".apt_generated/",
			"deploy-path": "/WEB-INF/classes/"
		}
	]
}
```

The org.eclipse.wst.common.component : 
```xml
<?xml version="1.0" encoding="UTF-8"?><project-modules id="moduleCoreId" project-version="1.5.0">
    <wb-module deploy-name="ProjectName">
        <wb-resource deploy-path="/" source-path="/target/m2e-wtp/web-resources"/>
        <wb-resource deploy-path="/" source-path="/src/main/webapp" tag="defaultRootSource"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/src/main/java"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/target/metamodel"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/src/main/resources"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/src/main/wsdl"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/conf"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/conf/dev/resources"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/.apt_generated"/>
        <property name="context-root" value="ProjectName"/>
        <property name="java-output-path" value="/ProjectName/target/classes"/>
        <property name="component.exclusion.patterns" value="WEB-INF/classes/com/,styles/scss/,styles/sites/"/>
    </wb-module>
</project-modules>
```

The server configuration : 

```json
{
  "args.override.boolean": "true",
  "args.program.override.string": "start",
  "args.shutdown.program.override.string": "stop",
  "args.shutdown.vm.override.string": "-Dcatalina.base=\"/home/me/web2\" -Dcatalina.home=\"/home/me/Documents/Developpement/tomcat/apache-tomcat-10.1.41\" -Dwtp.deploy=\"/home/me/web2/wtpwebapps\" -Djava.library.path=\"/home/me/Documents/Developpement/tomcat/apache-tomcat-10.1.41/bin\" --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED",
  "args.vm.override.string": "-Dcatalina.base=\"/home/me/web2\" -Dcatalina.home=\"/home/me/Documents/Developpement/tomcat/apache-tomcat-10.1.41\" -Dwtp.deploy=\"/home/me/web2/wtpwebapps\" -Djava.library.path=\"/home/me/Documents/Developpement/tomcat/apache-tomcat-10.1.41/bin\" --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED",
  "id": "Tomcat 10.x",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.100",
  "server.base.dir": "/home/me/web2",
  "server.classpath.additions": "",
  "server.deploy.dir": "${server.base.dir}/wtpwebapps/",
  "server.home.dir": "/home/me/Documents/Developpement/tomcat/apache-tomcat-10.1.41",
  "server.http.host": "localhost",
  "server.http.port": "8080",
  "vm.install.path": "/usr/lib/jvm/java-17-openjdk-amd64",
  "deployables": {
    "/home/me/git/projectName": {
      "label": "/home/me/git/projectName",
      "path": "/home/me/git/projectName",
      "options": {
        "option": {
          "deployment.assembly.file": ".rsp/rsp.assembly.json"
        }
      }
    }
  }
}
```

**Comment by robstryker** [comment]
Sorry for the delay. 

Your assembly file looks ok on first glance? Where have you actually placed this assembly file? The expected location is `.rsp/rsp.assembly.json`

**Comment by ExodusG** [comment]
no problem, yeah the rsp file was in the correct location. Interesting thing, when i try to change the path of the  deployment.assembly.file on the configuration server, the json revert to .rsp/rsp.assembly.json. I dont know if the "deployables" in the configuration server is correct ?

**Comment by ExodusG** [comment]
So I tried different things, and I think I have found the problem. I changed the configuration of the server to: 
```
  "deployables": {
    "/home/me/git/projectName": {
      "label": "/home/me/git/projectName",
      "path": "/home/me/git/projectName",
      "options": {
        "option": {
          "deployment.output.name": "projectName"
        }
      }
    }
  }
```
And now it works! Maybe it’s the custom options of deployment.assembly.file?

By the way, when you change the rsp.assembly.json, the deployment doesn’t take the new version. I have to remove the deployment (when it works, because sometimes the deployment doesn’t remove properly and I have to remove the server) and re-add the deployment to see the change.

``̀`
{
			"source-path": "src/main/java/",
			"deploy-path": "/WEB-INF/classes/"
}```

to : 

```
{
			"source-path": "target/classes/",
			"deploy-path": "/WEB-INF/classes/"
		},
		{
			"source-path": "target/projectName/WEB_INF/lib",
			"deploy-path": "/WEB-INF/classes/lib"
		},
```
I had to change the assembly because before it copied the .java files instead of the .class files like Eclipse does.
Now I have another issue:
```
[onPool-worker-4] ERROR o.j.t.r.s.s.p.AbstractFilesystemPublishController:289 - Error publishing module /home/me/git/projectName to server Tomcat 10.x (1): error copying mapping /home/me/git/projectName/target/classes to /home/me/web2/wtpwebapps/projectName/WEB-INF/classes
java.nio.file.NoSuchFileException: /home/me/web2/wtpwebapps/projectName/WEB-INF/classes/parametrage.properties
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
....
```
Maybe it's related with is : [https://github.com/redhat-developer/rsp-server-community/issues/235#issuecomment-3314741932](https://github.com/redhat-developer/rsp-server-community/issues/235#issuecomment-3314741932)  or [https://github.com/redhat-developer/rsp-server-community/issues/233](https://github.com/redhat-developer/rsp-server-community/issues/233) ?

**Comment by robstryker** [comment]
So, I fixed that bug almost a year ago but I got assigned some different work and never released the fix. I'm working on pushing out releases now.

**Comment by ExodusG** [comment]
You are talking about the deployment.assembly.file bug or about the "ERROR o.j.t.r.s.s.p.AbstractFilesystemPublishController:289 - Error publishing module" ?

**Comment by robstryker** [comment]
I'm referring to the publish failure. 

As for the issue regarding having to undeploy and redeploy when changing the deployment configuration, I believe this was a design decision, as we didn't want to make such large automatic changes when someone changes a json descriptor. 

For your other comment, regarding the source-path / deploy-path, yes, you need to point to the specific folders you want mapped. Eclipse used to do the mapping for you, but, it required a tighter access to the eclipse jdt model than we have in vscode, which was impossible for us.

**Comment by ExodusG** [comment]
Thanks for your time and your response.
So for the publish failure ```ERROR o.j.t.r.s.s.p.AbstractFilesystemPublishController:289 - Error publishing module```  you have publish the releases yesterday on the resp-server-community or you will do that later ? 
I will check for add PostResources on the tomcats server directly

**Comment by robstryker** [comment]
The bug was in the rsp-server repository. This is the base layer of the backend, and also has support for wildfly / eap.  This was released.  Then vscode-server-connector, which bundles this, was released. 

After that, the rsp-server-community repository was also released. This repository depends on the above base layer, and so any fixes in the base layer get incorporated here as well. This repository contains and builds two main artifacts. The first is a backend process for community servers like tomcat, glassfish, liberty, etc. The second is the vscode extension which then bundles that. 

After that, a bug in vscode-rsp-ui regarding the console stealing focus, which was fixed 9 months ago but never released, was also released. 

So, the whole stack was pretty much released this past week.

**Comment by ExodusG** [comment]
ok thanks. So i have try with all the extension up to date but I still have the ```Error publishing module```

**Comment by robstryker** [comment]
Can you please include more of the stacktrace?

**Comment by ExodusG** [comment]
of corse : 

```
[pool-1-thread-1] ERROR o.j.t.r.s.s.p.AbstractFilesystemPublishController:289 - Error publishing module /home/me/git/projectName to server Tomcat 10.x: error copying mapping /home/me/git/projectName/target/classes to /home/me/web2/wtpwebapps/projectName/WEB-INF/classes
java.nio.file.NoSuchFileException: /home/me/web2/wtpwebapps/projectName/WEB-INF/classes/parametrage.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController$CopyFileVisitor.visitFile(AbstractFilesystemPublishController.java:465)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController$CopyFileVisitor.visitFile(AbstractFilesystemPublishController.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController.fullPublishCopyExplodedModule(AbstractFilesystemPublishController.java:285)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController.fullPublishCopyModule(AbstractFilesystemPublishController.java:243)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController.copyModule(AbstractFilesystemPublishController.java:190)
	at org.jboss.tools.rsp.server.spi.publishing.AbstractFilesystemPublishController.publishModule(AbstractFilesystemPublishController.java:165)
	at org.jboss.tools.rsp.server.generic.servertype.GenericServerBehavior.publishDeployable(GenericServerBehavior.java:480)
	at org.jboss.tools.rsp.server.model.AbstractServerDelegate.publish(AbstractServerDelegate.java:508)
	at org.jboss.tools.rsp.server.model.AbstractServerDelegate.publish(AbstractServerDelegate.java:479)
	at org.jboss.tools.rsp.server.model.ServerModel$2.run(ServerModel.java:701)
	at org.jboss.tools.rsp.server.spi.jobs.SimpleJob.run(SimpleJob.java:100)
	at org.jboss.tools.rsp.server.jobs.JobManager.lambda$0(JobManager.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ExodusG** [comment]
Hey, sorry to bother you, did you have time to check about the stacktrace ?

**Comment by ExodusG** [comment]
hey, I hope you are fine ! I still have the issue :/
